spring.application.name=ExamenFinal

spring.datasource.url=jdbc:postgresql://dpg-d8r13ir6ac1c73bdj49g-a.oregon-postgres.render.com:5432/dafne_db
spring.datasource.username=dafne_db_user
spring.datasource.password=49GndSPsb6H5GLYLenkxzppciF4cnaNy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect